language: ruby
sudo: false
# cache: bundler
bundler_args: --without development
before_install:
  - gem update --system
  - gem update bundler
  - gem --version
  - bundle --version
rvm:
  - 2.3.7
  - 2.4.4
  - 2.5.1
  - jruby
  - ruby-head
matrix:
  include:
    - rvm: ruby-head
      gemfile: gemfiles/Gemfile.capybara_master
  allow_failures:
    - rvm: jruby
    - rvm: ruby-head
