language: ruby
bundler_args: --without development
before_install:
  - gem update --system
  - gem update bundler
  - gem --version
  - bundle --version
rvm:
  - 2.3
  - 2.4
  - 2.5
  - jruby
  - ruby-head
gemfile:
  - Gemfile
  - gemfiles/Gemfile.capybara_2.4
matrix:
  include:
    - rvm: ruby-head
      gemfile: gemfiles/Gemfile.capybara_master
  allow_failures:
    - rvm: jruby
    - rvm: ruby-head

