language: ruby
sudo: false
before_install:
  - gem update --system
  - gem update bundler
  - gem --version
  - bundle --version
rvm:
  - 2.6
  - 2.7
  - 3.0
  - 3.1
  - jruby
  - ruby-head
gemfile:
  - Gemfile
  - gemfiles/Gemfile.capybara_2
matrix:
  include:
    - rvm: ruby-head
      gemfile: gemfiles/Gemfile.capybara_master
  allow_failures:
    - rvm: jruby
    - rvm: ruby-head

