# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{capybara-mechanize}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Jeroen van Dijk"]
  s.date = %q{2010-08-12}
  s.summary = %q{RackTest driver for Capybara with remote request support}
  s.description = %q{RackTest driver for Capybara, but with remote request support thanks to mechanize}

  s.email = %q{jeroen@jeevidee.nl}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "spec/spec.opts",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/jeroenvandijk/capybara-mechanize}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.test_files = [
    "spec/driver/mechanize_spec.rb",
     "spec/spec_helper.rb"
  ]

  s.add_dependency(%q<mechanize>, ["= 1.0.0"])
  s.add_dependency(%q<capybara>, ["= 0.3.9"])
  s.add_development_dependency(%q<rspec>, ["= 1.3.0"])
end

