# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{capybara-mechanize}
  s.version = "0.2.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Jeroen van Dijk"]
  s.date = %q{2010-10-04}
  s.description = %q{RackTest driver for Capybara, but with remote request support thanks to mechanize.}
  s.email = %q{jeroen@jeevidee.nl}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.mdown"
  ]
  s.files = [
    ".document",
     ".gitignore",
     ".rspec",
     "Gemfile",
     "Gemfile.lock",
     "LICENSE",
     "README.mdown",
     "Rakefile",
     "VERSION",
     "capybara-mechanize.gemspec",
     "lib/capybara/driver/mechanize_driver.rb",
     "lib/capybara/mechanize.rb",
     "lib/capybara/mechanize/cucumber.rb",
     "lib/capybara/spec/extended_test_app.rb",
     "spec/driver/mechanize_driver_spec.rb",
     "spec/driver/remote_mechanize_driver_spec.rb",
     "spec/session/mechanize_spec.rb",
     "spec/session/remote_mechanize_spec.rb",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/jeroenvandijk/capybara-mechanize}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{RackTest driver for Capybara with remote request support.}
  s.test_files = [
    "spec/driver/mechanize_driver_spec.rb",
     "spec/driver/remote_mechanize_driver_spec.rb",
     "spec/session/mechanize_spec.rb",
     "spec/session/remote_mechanize_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<mechanize>, ["~> 1.0"])
      s.add_development_dependency(%q<rspec>, [">= 2.0.0.beta.22"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_development_dependency(%q<sinatra>, [">= 0"])
      s.add_development_dependency(%q<mongrel>, [">= 1.2.pre"])
    else
      s.add_dependency(%q<mechanize>, ["~> 1.0"])
      s.add_dependency(%q<rspec>, [">= 2.0.0.beta.22"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<sinatra>, [">= 0"])
      s.add_dependency(%q<mongrel>, [">= 1.2.pre"])
    end
  else
    s.add_dependency(%q<mechanize>, ["~> 1.0"])
    s.add_dependency(%q<rspec>, [">= 2.0.0.beta.22"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<sinatra>, [">= 0"])
    s.add_dependency(%q<mongrel>, [">= 1.2.pre"])
  end
end

